// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-cXMeKgk7x1Vg93km7OZqc1wefmXueII',
    appId: '1:360789839152:web:8dcce1f2600360873f0cf5',
    messagingSenderId: '360789839152',
    projectId: 'smart-quiz-ee243',
    authDomain: 'smart-quiz-ee243.firebaseapp.com',
    storageBucket: 'smart-quiz-ee243.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8p8qsUNScY5snAddkVxLwOMnpYitloSA',
    appId: '1:360789839152:android:e110371f05701f3a3f0cf5',
    messagingSenderId: '360789839152',
    projectId: 'smart-quiz-ee243',
    storageBucket: 'smart-quiz-ee243.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2_s0AVAFmqIMFCoQ80P9eDRjZI_Ccymc',
    appId: '1:360789839152:ios:6b244fef2c87c7be3f0cf5',
    messagingSenderId: '360789839152',
    projectId: 'smart-quiz-ee243',
    storageBucket: 'smart-quiz-ee243.firebasestorage.app',
    iosBundleId: 'com.example.smartQuizApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2_s0AVAFmqIMFCoQ80P9eDRjZI_Ccymc',
    appId: '1:360789839152:ios:6b244fef2c87c7be3f0cf5',
    messagingSenderId: '360789839152',
    projectId: 'smart-quiz-ee243',
    storageBucket: 'smart-quiz-ee243.firebasestorage.app',
    iosBundleId: 'com.example.smartQuizApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-cXMeKgk7x1Vg93km7OZqc1wefmXueII',
    appId: '1:360789839152:web:bbfab6a43897dd773f0cf5',
    messagingSenderId: '360789839152',
    projectId: 'smart-quiz-ee243',
    authDomain: 'smart-quiz-ee243.firebaseapp.com',
    storageBucket: 'smart-quiz-ee243.firebasestorage.app',
  );
}
